# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoRxSwift

  target 'DemoRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxSwift',    '~> 3.0'
    	pod 'RxCocoa',    '~> 3.0'
  end

  target 'DemoRxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxSwift',    '~> 3.0'
    	pod 'RxCocoa',    '~> 3.0'
  end

end
